combat-check-interval: 5 # in ticks
tag-time: 5000 #in ms
executable-commands-during-combat:
  - '/msg'
  - '/r'
messages:
  you-can-not-execute-this-command: '&cYou cannot execute this command during combat.'
  you-are-tagged: '&cYou are in combat right now. Do not quit from game.'
  you-are-untagged: '&cYou are no longer combat. You''re safe'
  you-can-not-open-inventory: '&cYou cannot open inventory during combat.'
  you-can-not-teleport: '&cYou cannot teleport during combat.'
timer:
  format: '&cYou are in combat for &f{time}s'
disabled-worlds:
  - combatlogwilldisabledthisworld