main: mc.obliviate.lightcombatlog.LightCombatLog
name: LightCombatLog
api-version: 1.13
version: 1.2.2
author: Mr_Obliviate
description: Lightweight combat log plugin
softdepend:
  - Multiverse-Core
  - WorldGuard
commands:
  lightcombatlog:
    description: reloads plugin
